name: Deploy to local runner
on:
    push:
      branches: [ main ]


jobs:
  deploy:
  # the job will only run on a runner that has the `self-hosted` + `local` labels
    runs-on: self-hosted


    steps:
        - name: Checkout code
          uses: actions/checkout@v4


        - name: Show workspace
          run: |
            echo "workspace: $GITHUB_WORKSPACE"
            ls -la "$GITHUB_WORKSPACE"

        - name: Sync to target folder on runner
          run: |
            # Get current date in yyyy-mm-dd format
            TODAY=$(date +'%Y-%m-%d')

            # Use $HOME instead of hardcoding your username
            TARGET_DIR="$HOME/Desktop/avif-express-$TODAY"

            # Save TARGET_DIR to env so other steps can use it
            echo "TARGET_DIR=$TARGET_DIR" >> $GITHUB_ENV

            # Create the target folder if it doesn't exist
            mkdir -p "$TARGET_DIR"

            # Copy repo contents (after cleanup) to the desired local path
            # if same machine: use rsync (no network)
            # If you need sudo to write to the target, prefix rsync with sudo.
            rsync -av --progress $GITHUB_WORKSPACE/ $TARGET_DIR \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '.idea' \
            --exclude '.editorconfig' \
            --exclude 'README.md' \
            --exclude '.gitignore' \
            --exclude 'readme-screens' \
            --exclude 'core/app/backend/assets/src' \
            --exclude 'core/app/backend/assets/stores' \
            --exclude 'core/app/backend/mix-manifest.json' \
            --exclude 'core/app/backend/package-lock.json' \
            --exclude 'core/app/backend/package.json' \
            --exclude 'core/app/backend/tailwind.config.js' \
            --exclude 'core/app/backend/webpack.mix.js' 

        - name: Verify deployment
          run: |
            echo "Deployment complete. Contents of $TARGET_DIR:"
            ls -la "$TARGET_DIR"

            